/*
-- Query: 
-- Date: 2012-04-05 18:46
*/
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (1,'Terror en Amityville',2005,'Terror','C','Jesse James, Jimmy Bennett, Melissa George, Rachel Nichols','Alquiler','Buena',10,15,0,'MGM',210,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (2,'Actividad Paranormal',2009,'Terror','B','Katie Featherston, Micah Sloat, Amber Armstrong','Alquiler','Buena',15,15,0,'Paramount Pictures',220,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (3,'American Pie: Fraternidad Beta',2007,'Comedia','C','John White, Jake Sieel, Nic Nac, Meghan Heffern, Steve Talley, Jordan Prentice, Jonathan Keltz, Tyrone Savage','Venta','Nueva',14,500,0,'Universal Pictures',200,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (4,'13 Hrs',2010,'Terror','C',' Isabella Calthorpe, Tom Felton, Gemma Atkinson, Joshua Bowman, Gabriel Thomson, Peter Gadiot, Antony De Liseo','Venta','Nueva',13,450,0,'MGM',180,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (5,'Destino Final 5',2011,'Terror','B',' Nicholas D''Agosto, Emma Bell, Miles Fisher, Arlen Escarpeta, Jacqueline MacInnes Wood, Ellen Wroe, P.J. Byrne','Alquiler','Buena',12,15,0,'Warner Bros',180,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (6,'La Huérfana',2009,'Terror','B','Isabelle Fuhrman, Jimmy Bennett, Lorry Ayers, Vera Farmiga','Venta','Nueva',11,620,0,'Warner Bros',220,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (7,'Los Otros',2001,'Terror','B',' Nicole Kidman, Fionnula Flanagan, Christopher Eccleston, Alakina Mann, James Bentley, Eric Sykes, Elaine Cassidy','Venta','Nueva',10,470,0,'Sogecine',150,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (8,'Dude, Where''s my Car?',2000,'Comedia','B','Ashton Kutcher, Seann William Scott, Kristy Swanson, Jennifer Garner, Marla Sokoloff, Hal Sparks','Alquiler','Buena',16,15,0,'20th Century Fox',190,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (9,'La Proposición',2009,'Comedia','B','Sandra Bullock, Ryan Reynolds, Mary Steenburgen, Craig T. Nelson, Betty White','Alquiler','Buena',15,15,0,'Buena Vista International',220,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (10,'The Bourne Ultimatum',2007,'Accion','C','Matt Damon, Julia Stiles, David Strathairn, Scott Glenn, Paddy Considine, Edgar Ramirez, Albert Finney, Joan Allen','Alquiler','Buena',14,15,0,'Universal Pictures',200,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (11,'X-Men Orígenes: Guepardo',2009,'Accion','A','Hugh Jackman, Liev Schreiber, Danny Huston, Dominic Monaghan , Ryan Reynolds, Taylor Kitsch, Kevin Durand','Alquiler','Buena',13,15,0,'20th Century Fox',170,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (12,'Rápidos y Furiosos: 5in Control',2011,'Accion','B','Vin Diesel, Paul Walker, Dwayne','Venta','Nueva',12,510,0,'Universal Pictures',190,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (13,'Harry Potter y las Reliquias de la Muerte: Parte II',2011,'Ciencia Ficcion','A','Daniel Radcliffe, Emma Watson, Rupert Grint, Alan Rickman, Ralph Fiennes, Helena Bonham Carter, Michael Gambon','Alquiler','Buena',11,15,0,'Warner Bros',150,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (14,'P.D. Te Amo',2007,'Romance','B','Hilary Swank, Gerard Butler, Lisa Kudrow, Harry Connick Jr., Gina Gershon, Jeffrey Dean Morgan, Kathy Bates','Venta','Nueva',10,580,0,'Warner Bros',210,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (15,'Papá Por Accidente',2010,'Romance','A','Jennifer Aniston, Jason Bateman, Thomas Robinson, Juliette Lewis, Patrick Wilson, Jeff Goldblum, Scott Elrod','Alquiler','Buena',9,15,0,'Miramax Films',220,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (16,'Gladiator',2000,'Drama','B','Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed, Derek Jacobi, Djimon Hounsou, Ralf Möller, Richard Harris','Venta','Nueva',8,440,0,'Universal Pictures',170,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (17,'You Dont Mess with the Zohan',2008,'Comedia','B','Adam Sandler, Emmanuelle Chriqui, John Turturro, Nick Swardson, Lainie Kazan, Rob Schneider, Chris Rock, Mariah Carey','Venta','Nueva',14,500,0,'Columbia Pictures',200,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (18,'Inception',2010,'Ciencia Ficcion','B','Leonardo DiCaprio, Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Ellen Page, Tom Hardy, Dileep Rao, Cillian Murphy, Tom Berenger, Michael Caine','Venta','Nueva',13,500,0,'Warner Bros',200,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (19,'The Dark Knight',2008,'Accion','B','Christian Bale, Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal, Morgan Freeman','Venta','Nueva',12,540,0,'Warner Bros',215,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (20,'Twilight',2008,'Romance','B','Kristen Stewart, Robert Pattinson, Billy Burke, Peter Facinelli','Alquiler','Buena',11,15,0,'Aurum',160,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (21,'The Twilight Saga: New Moon',2009,'Romance','B','Kristen Stewart, Robert Pattinson, Taylor Lautner, Ashley Greene, Rachelle Lefevre, Billy Burke, Michael Sheen, Dakota Fanning','Alquiler','Buena',10,15,0,'Aurum',195,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (22,'The Twilight Saga: Eclipse',2010,'Romance','B','Kristen Stewart, Robert Pattinson, Taylor Lautner, Bryce Dallas Howard, Billy Burke, Dakota Fanning','Alquiler','Buena',9,15,0,'Aurum',200,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (23,'The Twilight Saga: Breaking Dawn. Parte I',2011,'Romance','B','Kristen Stewart, Robert Pattinson, Taylor Lautner','Alquiler','Buena',8,15,0,'Aurum',210,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (24,'The Twilight Saga: Breaking Dawn. Parte II',2012,'Romance','B','Kristen Stewart, Robert Pattinson, Taylor Lautner','Alquiler','Buena',13,15,0,'Aurum',185,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (25,'The Chronicles of Narnia: Prince Caspian',2008,'Ciencia Ficcion','A','Ben Barnes, Georgie Henley, Skandar Keynes, William Moseley, Anna Popplewell, Liam Neeson, Sergio Castellitto, Peter Dinklage','Venta','Nueva',12,540,0,'Walt Disney Pictures',215,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (26,'The Chronicles of Narnia: The Voyage of the Dawn Treader',2010,'Ciencia Ficcion','A','Georgie Henley, Skandar Keynes, Will Poulter, Ben Barnes, Liam Neeson, Simon Pegg','Venta','Nueva',11,540,0,'Walt Disney Pictures',215,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (27,'Zombieland',2009,'Comedia','B','Woody Harrelson, Jesse Eisenberg, Emma Stone, Abigail Breslin','Alquiler','Buena',10,15,0,'Columbia Pictures',250,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (28,'The Social Network',2010,'Drama','B','Jesse Eisenberg, Andrew Garfield, Justin Timberlake, Armie Hammer, Max Minghella, Brenda Song, Rashida Jones, Rooney Mara','Alquiler','Buena',9,15,0,'Sony Pictures',210,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (29,'In Time',2011,'Ciencia Ficcion','B','Justin Timberlake, Amanda Seyfried, Cillian Murphy, Olivia Wilde, Alex Pettyfer, Vincent Kartheiser, Johnny Galecki','Venta','Nueva',8,510,0,'20th Century Fox',190,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (30,'The Last Samurai',2003,'Drama','B','Tom Cruise','Alquiler','Buena',7,15,0,'Warner Bros',230,'2012-01-15','2012-01-30','2012-01-30','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (31,'Hugo',2011,'Drama','A','Asa Butterfield, Ben Kingsley, Chloë Grace Moretz, Sacha Baron Cohen, Richard Griffiths, Frances de la Tour, Ray Winstone, Emily Mortimer, Jude Law, Christopher Lee','Venta','Nueva',6,550,0,'Paramount Pictures',190,'2012-02-28','2012-03-10',NULL,'Pedido',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (32,'Pineapple Express',2008,'Comedia','C','Seth Rogen, James Franco, Gary Cole, Rosie Perez, Craig Robinson, Amber Heard, Kevin Corrigan, Danny R. McBride','Alquiler','Dañada',5,15,10,'Columbia Pictures',180,'2011-11-10','2011-12-01','2011-12-02','Disponible',NULL,'Caducado');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (33,'Terror en Amityville',2005,'Terror','C','Jesse James, Jimmy Bennett, Melissa George, Rachel Nichols','Alquiler','Buena',10,15,0,'MGM',210,'2011-11-10','2011-12-01','2011-12-20','Disponible',NULL,'Vigente');
INSERT INTO `Peliculas` (`idPelicula`,`Titulo`,`Año`,`Genero`,`Censura`,`Reparto`,`Uso`,`Condicion`,`Cantidad`,`Precio`,`Veces_Alquilada`,`Distribuidor`,`Precio_Pedido`,`Fecha_Solicitud`,`Fecha_Esperada`,`Fecha_Entrega`,`Estatus`,`idAuxiliar`,`Registro`) VALUES (34,'American Pie: Fraternidad Beta',2007,'Comedia','C','John White, Jake Sieel, Nic Nac, Meghan Heffern, Steve Talley, Jordan Prentice, Jonathan Keltz, Tyrone Savage','Venta','Nueva',14,500,0,'Universal Pictures',200,'2012-01-15','2011-12-01','2011-12-20','Disponible',NULL,'Vigente');
